# Generated by Django 6.0.6 on 2026-06-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("BANNER", "Промо-баннер"),
                            ("CATEGORY_GRID", "Сетка категорий"),
                            ("PRODUCT_CAROUSEL", "Карусель товаров"),
                        ],
                        max_length=50,
                        verbose_name="Тип блока",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Для BANNER: {'title': '...', 'image_url': '...'} | Для CATEGORY_GRID: {'category_ids': [1, 2]}",
                        verbose_name="Данные блока (JSON)",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Блок главной страницы",
                "verbose_name_plural": "Блоки главной страницы",
                "ordering": ["sort_order"],
            },
        ),
    ]
