# Generated by Django 6.0.6 on 2026-06-07 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название категории"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Слаг (URL)",
                    ),
                ),
                (
                    "crm_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID группы блюд в кассе. Не менять!",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="ID в r-keeper (RK7)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="menu/categories/",
                        verbose_name="Изображение категории",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Категория меню",
                "verbose_name_plural": "Категории меню",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название товара"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=200,
                        unique=True,
                        verbose_name="Слаг (URL)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание / Состав"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="menu/products/",
                        verbose_name="Изображение товара",
                    ),
                ),
                (
                    "crm_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID блюда в кассе. Не менять!",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="ID в r-keeper (RK7)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Отображать в меню"),
                ),
                (
                    "is_out_of_stock",
                    models.BooleanField(default=False, verbose_name="Стоп-лист"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="menu.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: '30 см', '40 см'",
                        max_length=100,
                        verbose_name="Название варианта",
                    ),
                ),
                (
                    "crm_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID модификатора в RK7",
                        max_length=50,
                        null=True,
                        verbose_name="ID варианта в r-keeper",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Цена"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Доступен для заказа"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="menu.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант товара",
                "verbose_name_plural": "Варианты товаров",
            },
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("category", "name"), name="unique_product_name_in_category"
            ),
        ),
    ]
