# Generated by Django 5.2.15 on 2026-06-10 14:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название категории"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Слаг (URL)",
                    ),
                ),
                (
                    "crm_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID группы блюд в кассе. Не менять!",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="ID в r-keeper (RK7)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="menu/categories/",
                        verbose_name="Изображение категории",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Категория меню",
                "verbose_name_plural": "Категории меню",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название товара"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=200,
                        unique=True,
                        verbose_name="Слаг (URL)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание / Состав"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="menu/products/",
                        verbose_name="Изображение товара",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, verbose_name="Цена"
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Если заполнено, на сайте будет отображаться как зачёркнутая цена",
                        max_digits=8,
                        null=True,
                        verbose_name="Старая цена (для скидки)",
                    ),
                ),
                (
                    "crm_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID блюда в кассе. Не менять!",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="ID в r-keeper (RK7)",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="Количество"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.001, message="Вес не может быть меньше 1 г"
                            ),
                            django.core.validators.MaxValueValidator(
                                999.999, message="Вес слишком большой"
                            ),
                        ],
                        verbose_name="Вес (кг)",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Отмечайте, если товар можно купить.",
                        verbose_name="В наличии?",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Отображать в меню"),
                ),
                (
                    "is_out_of_stock",
                    models.BooleanField(default=False, verbose_name="Стоп-лист"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="menu.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "name"),
                        name="unique_product_name_in_category",
                    )
                ],
            },
        ),
    ]
